
version: '3.3'

services:

  #backend:
  #  build: ./backend

 # db:
 #   build: ./db
 #   restart: always
    #volumes: 
    #  - ./db/dbdir:/var/lib/mysql
 #   environment:
 #       MYSQL_ROOT_PASSWORD: root

 # db-editor:
 #   build: ./db-editor
 #   restart: always
 #   ports: 
 #     - "6080:8080"
  #backend:
  #  build: ./backend
  #  ports: 
  #    - "6081:8080"
  #  environment:
  #    -  MYSQL_HOSTNAME:localhost
  #    -  MYSQL_PORT:3306
  #    -  MYSQL_USERNAME:root
  #    -  MYSQL_PASSWORD:root
  #    -  MYSQL_DBNAME:db
  #
  frontend:
    build: ./frontend
    restart: always
    #затирает текущую папку
    volumes:
     - ./frontend/dist:/app/code/dist
    ports:
     - "8080:80"