
version: '3'

services:

  db:
    build: ./db
    restart: always
    volumes: 
    #затирает текущую папку
    #  - ./db/data-volume:/var/lib/mysql
      - ./db/db.sql:/docker-entrypoint-initdb.d/init.sql
    #  - ./db/conf:/etc/mysql/conf.d
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test

  db-editor:
    build: ./db-editor
    restart: always
    ports: 
      - "${DB_EDITOR_PORT}:8080"
  #backend:
  #  build: ./backend
    #ports: 
    #  - "7080:8080"
  #  ports:
  #   - "443:443"
  
  frontend:
    build: ./frontend
    restart: always
    #затирает текущую папку
  #  volumes:
  #   - ./frontend/dist:/app/code
    ports:
     - "${WEB_PORT}:80"
     - "443:443"