
version: '3'

services:

  db:
    build: ./db
    restart: always
    volumes: 
    #затирает текущую папку
    #  - ./db/data-volume:/var/lib/mysql
      - ./db/db.sql:/docker-entrypoint-initdb.d/init.sql
    #  - ./db/conf:/etc/mysql/conf.d
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test

  db-editor:
    build: ./db-editor
    restart: always
    #links:
    #- db
    ports: 
      - "6080:8080"
  backend:
    build: ./backend
    #ports: 
    #  - "7080:8080"
    #environment:
    #  -  MYSQL_HOSTNAME:localhost
    #  -  MYSQL_PORT:3306
    #  -  MYSQL_USERNAME:root
    #  -  MYSQL_PASSWORD:root
    #  -  MYSQL_DBNAME:test
    ports:
     - "443:443"
  
  frontend:
    build: ./frontend
    restart: always
    #затирает текущую папку
  #  volumes:
  #   - ./frontend/dist:/app/code
    ports:
     - "8080:80"
     - "443:443"