
version: '3'

services:

  nginx:
    build: ./nginx
    restart: always
    volumes:
     - ./www/front:/var/www
#     - ./nginx/config:/etc/nginx
     - ./nginx/logs:/var/log/nginx

    ports:
     - "8080:80"
     - "443:443"
    links:
     - backend
     
  backend:
    build: ./backend
#    volumes:
#      - ./www/back:/var/www
    links:
      - db

  db:
    build: ./db
    restart: always
    volumes: 
    #затирает текущую папку
    #  - ./db/data-volume:/var/lib/mysql
      - ./www/db/db.sql:/docker-entrypoint-initdb.d/init.sql
    #  - ./db/conf:/etc/mysql/conf.d
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
    ports: 
      - "3306:3306"

  db-editor:
    build: ./db-editor
    restart: always
    ports: 
      - "6080:8080"

  
