
version: '3'

services:

  nginx:
    build: ./nginx
    volumes:
     - ./nginx/www:/usr/share/nginx/html
     - ./nginx/config:/usr/local/nginx/conf

    ports:
     - "8080:80"
     - "443:443"
    links:
     - backend
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend/www:/var/www/html
    ports:
      - "8100:80"
#    links:
#      - db
#    - nginx
#    depends_on:
#      - db

#  db:
#    build: ./db
#    restart: always
#    command: --innodb_use_native_aio=0
#    volumes: 
#     - ./www/db/db.sql:/docker-entrypoint-initdb.d/init.sql
#    environment:
#        MYSQL_ROOT_PASSWORD: root
#        MYSQL_DATABASE: test
#    ports: 
#      - "3306:3306"
#
#  db-editor:
#    build: ./db-editor
#    restart: always
#    ports: 
#      - "6080:8080"
#    depends_on:
#      - db

  
